Mouse Engine event messaging system documentation.
This document describes the Mouse Engine event messaging system (EMS).
Copyright (C) <2026>  <James Hicks>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

* Event Messaging System Specification Sheet
** Author: James Hicks
* Purpose of the EMS
User input can come into the game unpredictably. Rather than busy-waiting for
input to come in we want to implement a publisher subscriber. Our implementation
will be asynchronous. I.E. The time that the event is registered is temporally
decoupled from the time the event is processed. For this decoupling we utilize
an event queue.

* Publisher
Events are asynchronously published to an event queue.

* Subscribers
Subscribing the an event type allows the user to process events out
of the event queue with the /event type/.


* Event Queue

* Asynchronous Event Processing

* The event loop
