Documentation for the platform abstraction layer.
Copyright (C) <2026>  <James Hicks>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

* platform abstraction layer (PAL) documentation
The platform abstraction layer provides a common interface between
Mouse Engine and the operating system. Platform specific implementations
expose a common API such that the rest of Mouse Engine remains portable.

* PAL Structure
Each platform dependent function has a platform-independent API that
it must implement. For example, Mouse Engine contains a file called
/mouse_window.h/. This file provides the public windowing API that
Mouse Engine uses. This file has no concept of platform, it just specifies
functions that each supported platform must implement.

Each platform must be detected, and platform specific implementations must
be includes. This is the job of /platform.h/. /platform.h/ detects the platform
and includes all platform specific headers.

Each platform must implement the API

* Supported platforms
** Linux
** Mac (planned)
** Windows (planned)

* Windowing API
** Linux
This module will be responsible for linux specific windowing calls.
* Logging
* Input
* Memory Allocation
* Networking
* Audio
