Documentation for the Mouse Windowing System.
Copyright (C) <2026>  <James Hicks>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
* window documentation
** Author: James Hicks
** Date Created: [2026-07-30 Thu]
** Date Last Modified: [2026-07-30 Thu]
*** Modification notes
- Creation of the document

* Xlib
- The Mouse Game windowing system depends on Xlib.

* X Window System
- A window has a border that is zero or more pixels in width
- A window usually has a background pattern the is repainted by the window system
  when not covered.
- Each window has [0,0] as their origin in the upper left corner of the window
- Coordinates coincide with pixel centers

** Connecting to the X Server
- To open a connection to the we call XOpenDisplay. This returns a `Display *`
  which will be static to the Mouse Windowing System translation unit.
- The Display structure serves as the connection to the X serve and contains
  all the information about the X server.
- XOpenDisplay() connects the engine to the X server through TCP or DECnet.


* Mouse Windowing System
** mouse_window_t struct
